version: '3.1'
services:
  backend-familiahuecas:
    container_name: backend-familiahuecas
    restart: "no"
    image: backend-familiahuecas
    ports:
      - "API_PUBLIC_PORT:API_PUBLIC_PORT"
      - "API_INTERNAL_PORT:API_INTERNAL_PORT"
    env_file:
      - ./backend.env
    links:
      - database-familiahuecas
    depends_on:
      - database-familiahuecas
    networks:
      - network
    volumes:
      - ./application.properties:/home/app/application.properties
      - ../log/backend:/log
      - /etc/localtime:/etc/localtime:ro
      
  database-familiahuecas:
    container_name: database-familiahuecas
    image: database-familiahuecas
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: CalleFalsa123
    ports:
      - "3306:3306"
    volumes:
      - datavolume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /etc/localtime:/etc/localtime:ro
      
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    networks:
      - network

  backoffice-familiahuecas:
    container_name: backoffice-familiahuecas
    image: backoffice-familiahuecas
    ports:
      - "BACKOFFICE_PORT:80"
    links:
      - backend-familiahuecas
    depends_on:
      - backend-familiahuecas
    networks:
      - network
    logging:
      driver: json-file
    env_file:
      - ./backoffice.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
     

  
  proxy-familiahuecas:
    container_name: proxy-familiahuecas
    image: proxy-familiahuecas
    ports:
      - "PROXY_HTTP_PORT:PROXY_HTTP_PORT"
      - "PROXY_HTTPS_PORT:PROXY_HTTPS_PORT"
    networks:
      - network
    logging:
      driver: json-file
    volumes:
      - ../certs:/etc/nginx/certs/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
      

volumes:
  datavolume:
    external: true

networks:
  network:
    driver: bridge
